# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_informationtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('link', models.URLField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.InformationTitle')),
            ],
        ),
    ]
