# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171025_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044e', 'verbose_name_plural': '\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='informationtitle',
            options={'verbose_name': '\u041f\u043e\u043b\u0435\u0437\u043d\u0443\u044e \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044e', 'verbose_name_plural': '\u041f\u043e\u043b\u0435\u0437\u043d\u0430\u044f \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044f'},
        ),
        migrations.RemoveField(
            model_name='information',
            name='type',
        ),
        migrations.AddField(
            model_name='informationtitle',
            name='steps',
            field=models.ManyToManyField(to='main.Information', verbose_name='\u0418\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u044e'),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=155, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='information',
            name='title_ch',
            field=models.CharField(max_length=155, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='information',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='information',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='informationtitle',
            name='title',
            field=models.CharField(max_length=155, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='informationtitle',
            name='title_ch',
            field=models.CharField(max_length=155, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='informationtitle',
            name='title_en',
            field=models.CharField(max_length=155, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='informationtitle',
            name='title_ru',
            field=models.CharField(max_length=155, null=True, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
