# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20171025_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0435\u043b\u0435\u0444\u043e\u043d\u0430'),
        ),
    ]
