# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20171025_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informationtitle',
            old_name='title',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='informationtitle',
            old_name='title_ch',
            new_name='type_ch',
        ),
        migrations.RenameField(
            model_name='informationtitle',
            old_name='title_en',
            new_name='type_en',
        ),
        migrations.RenameField(
            model_name='informationtitle',
            old_name='title_ru',
            new_name='type_ru',
        ),
    ]
